version: '3.6'

services:
  management.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "32823:80"
      - "32822:443"

  user.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "32821:80"
      - "32820:443"

  policy.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "32819:80"
      - "32818:443"